### ISSUE TITLE
Skriv navnet ditt  i "JegVarHer.txt" og få endringen opp på github

### ISSUE THREAD

**Issue by uansett** [hiofenigma/Toss#1]

**Comment by anskaal** [comment]
Prøvde å legge til "read+write"-repo i Eclipse (ssh-connection). Fikk auth-error. Skal man bruke git som user?

**Comment by uansett** [comment]
du m nok sette opp ssh-sertifikat for  koble opp. det glemte jeg helt  si p mtet! Men det er en tutorial p github om det :) hper det var greia og at det ikke er noe annet!

## 

Stian Johansen
stian.uansett@gmail.com
stianj@hiof.no

**Comment by Onizuka89** [comment]
Dere er klar over at det er meningen å close ting når det er gjort? :P Kan være greit å få inn det tidlig, bare sånn i fall issue greiene blir brukt en del. :P er litt vanskeligere å finne fram når dere har issues dere er ferdig med men ikke closed ;P
