### ISSUE TITLE
Lag et førsteutkast til grovt flytskjema over hele systemet - legg ut på forumet

### ISSUE THREAD

**Issue by uansett** [hiofenigma/Toss#6]
Lag:
Frontend
<Kommunikasjonsplattform>
Backend

**Comment by Onizuka89** [comment]
Anders Skaalsveen har gjort det, så jeg vil si at denne issue'en kan bli closed :)

**Comment by anskaal** [comment]
Definer isåfall grovt. :)

**Comment by uansett** [comment]
Gjør så detaljert du vil, men poenget er at vi skal rive det i filler etterpå :)

## 

Stian Johansen
Stian.uansett@gmail.com
Stianj@hiof.no

On 2. des. 2011, at 00:13, Anders Skaalsveen
reply@reply.github.com
wrote:

**Comment by anskaal** [comment]
Da sier vi close enough.

**Comment by ventrec** [comment]
Det ble veldig bra. Er sikkert noen ting som mangler, men det gir jo en god oversikt over hvordan ting er tenkt.

**Comment by uansett** [comment]
Jeg likte det ogs veldig godt. N jobber jeg med prosjektinnlevering s har ikke hatt tid til  forst det, men det ser veldig bra ut gutter :) dere kan close den

## 

Stian Johansen
stian.uansett@gmail.com
stianj@hiof.no
